name: "gd-if"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 630


data_type: "random-camera-datamodule"
data:
  batch_size: [4, 1]
  width: [64, 128]
  height: [64, 128]
  resolution_milestones: [5000, ]

  camera_distance_range: [1.5, 2.0]
  fovy_range: [40, 70]
  elevation_range: [-10, 90]
  light_sample_strategy: "dreamfusion"
  eval_camera_distance: 2.0
  eval_fovy_deg: 70.
  n_val_views: 5


system_type: "gdreamer-system"
system: 

  cleanup_after_validation_step: true
  
  # 01
  geometry_type: "gdreamer-implicit-sdf"
  geometry:    
    radius: 2.0
    normal_type: finite_difference
    finite_difference_normal_eps: progressive
    n_feature_dims: 3

    sdf_bias: learning
    center_params: [[], ]
    radius_params: []
    sdf_center_init_up: 0.  # +z
    sdf_center_init_right: 0.  # +y
    sdf_center_init_front: 0.  # +x
    sdf_center_dispersion: 0.2

    # coarse to fine hash grid encoding
    pos_encoding_config:
      otype: ProgressiveBandHashGrid
      n_levels: 10
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.41421356237309  # max resolution ~512
      start_level: 6  # resolution ~128
      start_step: 2000
      update_steps: 500
        
  # 02
  material_type: "diffuse-with-point-light-material"
  material:
    albedo_activation: sigmoid
    input_feature_dims: ${system.geometry.n_feature_dims}
  
  # 03
  background_type: "coordinate-background"
  background:
    color_activation: sigmoid
    random_aug: true
    # eval_color: None
  
  # 04
  renderer_type: "gdreamer-neus-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512
    cos_anneal_end_steps: ${trainer.max_steps}
  
  # 06
  prompt_global: []
  prompt_obj: []
  prompt_obj_neg: []
  obj_use_prompt_debiasing: false

  # DeepFloyd-IF Guidance <<<
  prompt_processor_type: "deep-floyd-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
    prompt: none
    # negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "deep-floyd-guidance"
  guidance:
    pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
    guidance_scale: 100.
    # guidance_scale: [50., 20.]
    # guidance_scale_milestones: [2000, ]
   
    weighting_strategy: sds
    min_step_percent: 0.02
    max_step_percent: [5000, 0.98, 0.5, 5001] # annealed to 0.5 after 5000 steps
    enable_memory_efficient_attention: true
  
  # 08
  loss:
    lambda_sds: 1.
    lambda_eikonal: 10.
    lambda_sdf: 10.
    lambda_inter: 100.
    lambda_entropy: 0.
    lambda_obj_sds: 1.
    lambda_obj_eikonal: 10.
  
  # 09
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry:
        lr: 0.001
      material:
        lr: 0.001
      background:
        lr: 0.001
      renderer:
        lr: 0.001
      guidance:
        lr: 0.0001

  loggers:
    wandb:
      enable: false
      project: 'threestudio'


trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 200
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}